name:                systemf
version:             0.1.0.0
github:              "Qbxs/SystemF-Typechecker"
license:             BSD3
author:              "Pascal Engel"
maintainer:          "pascal.engel@uni-tuebingen.de"
copyright:           "2021 Pascal Engel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Qbxs/SystemF-Typechecker#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- parsec

library:
  source-dirs: src

executables:
  systemf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - systemf
    - ansi-terminal

tests:
  systemf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - systemf
